### ISSUE TITLE
Loop of bot replies 

### ISSUE THREAD

**Issue by KITSPaulCousins** [athieriot/hubot-yammer#26]
Hey , love the yammer bot , its great. Got mine up and working with our enterprise yammer and it replies but seems to loop and reply the same message ,hits about 15 replies and then limit reached , any thoughts ?

Message creation status :201

Thanks for the effort.

**Comment by emedvedev** [comment]
Hi! What plugin/command do you use? Do you have the same error if you use the shell adapter? I don't remember anything that would make the adapter loop messages off the top of my head, and we didn't have this problem before, so it could be a faulty plugin.

**Comment by KITSPaulCousins** [comment]
Hi , its not occurring in the shell adapter ...edited the example.coffee for the hello and its response
output below , it sees message and then once complete see's the message again and repeats
=
groups list : Hubot
groups_ids list : 8050160
received Hello from jacobquieros (thread_id: 703755607, sender_id: 1556147454)
reply message to jacobquieros with text Hello welcome to Kingfisher what can I do for You?
Message creation status 201
received Hello welcome to Kingfisher what can I do for You? from jacobquieros,paulcousins (thread_id: 703755607, sender_id: 1528103644)
reply message to jacobquieros,paulcousins with text Hello welcome to Kingfisher what can I do for You?
Message creation status 201

**Comment by emedvedev** [comment]
Do you use `hear` and `respond` in your script? On `hear`, bot will respond to "hello" from anyone (including itself, which obviously shouldn't happen), hence the cycle. On `respond` it will only respond to people addressing it by alias, which is usually preferred. In both cases the loop would be a bug, but it's much weirder on `respond`. :)

**Comment by KITSPaulCousins** [comment]
I think I get it cause I have still have variable on for the self reply so its then replying to my own response , DOHHHH

**Comment by emedvedev** [comment]
Oh, right. If you have `process.env.HUBOT_YAMMER_REPLY_SELF`, it's expected behaviour. :) Should I close the issue?

**Comment by KITSPaulCousins** [comment]
Yep you can close the issue , thanks for the quick response , I was just lacking coffee
