### ISSUE TITLE
Hubot will not respond to through yammer adapter ...

### ISSUE THREAD

**Issue by anshumanpurohit** [athieriot/hubot-yammer#5]
I exported all the env properties required (noted in the WIKI) and then started hubot with the following command:

bin/hubot -a yammer -n "Hubot yammer name"

No error ... subscription goes in successfully.

Using another yammer account I send "updates" (e.g. "hubot ping", "hubot help" etc) to the group listed in HUBOT_YAMMER_GROUPS, but get NO reply back. Don't know where to look next.

**Comment by krishna1990fis** [comment]
@anshumanpurohit @athieriot Hey guys i could see that u have successfully able to integrate the yammer with hubot. i am facing some issue pertaining to that.
1. when i run bin\hubot -a yammer -n testhubot, i get following error
![image](https://cloud.githubusercontent.com/assets/16776975/21604707/c788ed42-d1ca-11e6-9a35-9fe17ee76b84.png)

2. this is how i have set env variable in bin\hubot folder
`export PORT=8080
export  HUBOT_YAMMER_ACCESS_TOKEN="{"user_id":1564529334,"network_id":81433,"network_permalink":"fisglobal.com","network_name":"FIS Global","token":"81433-qZlaPZbgokuCKdpiHnhK2Q","view_members":true,"view_groups":true,"view_messages":true,"view_subscriptions":true,"modify_subscriptions":true,"modify_messages":true,"view_tags":true,"created_at":"2016/12/23 10:26:11 +0000","authorized_at":"2016/12/23 10:26:11 +0000","expires_at":null}"
export HUBOT_YAMMER_GROUPS="chatbot_Hubot"` is this proper way of using a access token on hubot side ?

**Comment by athieriot** [comment]
I believe the token should only be the value of the "token" property. In your case: ```81433-qZlaPZbgokuCKdpiHnhK2Q``` (Not the whole thing)

I must warn you though that this is very very unsafe to publish the token value publicly and I would advice you to regenerate it.

**Comment by krishna1990fis** [comment]
@athieriot thanks for making me aware.
what is the solution for my first question, im getting" No group registered or an error occurred to resolve IDs. Please double click the image attached.

**Comment by athieriot** [comment]
In order to log itself to the specified Group, Hubot need to make a call to Yammer using the API and the given Token.

I suspect that, if you specify a valid token and the Group exists, the error should disappear.

**Comment by krishna1990fis** [comment]
Do i have to replace the access token value in the yammer.coffee file ?
run: ->
    options =
      access_token: process.env.HUBOT_YAMMER_ACCESS_TOKEN
      groups:       process.env.HUBOT_YAMMER_GROUPS or "hubot"
      reply_self:   process.env.HUBOT_YAMMER_REPLY_SELF

Or just need to set the value in bin\hubot folder file, like
export HUBOT_YAMMER_ACCESS_TOKEN="X14XX-XXXXXXXXXXXXXXXXXX"

**Comment by athieriot** [comment]
Using Env Variable (Using export) is the right way to do it.
It doubt, you should never have to edit a file yourself really.

**Comment by krishna1990fis** [comment]
i have tried that aswell, without editing the yammer.coffee file.
i have put 
export PORT=8080
export HUBOT_YAMMER_GROUPS="chatbot_Hubot"
export HUBOT_YAMMER_ACCESS_TOKEN="XXXXXXXX-XXXXXXXXXXX"
In my bin\hubot folder, but it is giving me following error 
![image](https://cloud.githubusercontent.com/assets/16776975/21606467/c95b1dce-d1d5-11e6-8f42-f64f3c43a126.png)

**Comment by athieriot** [comment]
Ok.
I never asked the question but I should have earlier.

Looking at your screenshot, I only see now that you are using Windows.
Sorry about that.
"export" only works for Unix system. (Or things like Cygwin)

With Windows, you have to use the keyword "set"

      set PORT=8080

If you want to check that the variables is properly set:

      set PORT

Alternatively, I know there is a Setting window somewhere you can use to
set Env Variable permanently but I don't remember exactly where

Sorry for the miss

**Comment by krishna1990fis** [comment]
I am setting env variable in bin\hubot file, and i have tried with set PORT = 8080, still im getting same error as "I need an access token"
How do i confirm that evn variables are set properly ?

**Comment by athieriot** [comment]
Just to be sure. You should use "set" for all of the variable, including the Token.

To display the current value of a variable, just use:

      set PORT

Or

      set HUBOT_YAMMER_ACCESS_TOKEN

**Comment by krishna1990fis** [comment]
In my bin folder i have two things
1. hubot file
2. hubot.cmd 
and hubot file contains this ->
`#!/bin/sh
set -e
npm install
set PATH="node_modules/.bin:node_modules/hubot/node_modules/.bin:$PATH"
exec node_modules/.bin/hubot --name "mib" "$@"

set PORT=8080
set HUBOT_YAMMER_GROUPS="chatbot_Hubot"
set HUBOT_YAMMER_ACCESS_TOKEN="UUUU-XXXXXXXXXXXXXXXX"`
 after doing this , if i open hubot.cmd and type set PORT then i am not getting anything .
![image](https://cloud.githubusercontent.com/assets/16776975/21607624/729d7cd6-d1dd-11e6-9b83-627cd169c844.png)

**Comment by athieriot** [comment]
Any Env Variable must be set BEFORE the exec statement, otherwise Hubot
won't see them.

Also, anything you set within the script will be local to that script, so
you won't see anything after the execution. (You could try to display the
value within the script though)

Le mar. 3 janv. 2017 à 12:23, krishna1990fis <notifications@github.com> a
écrit :

**Comment by krishna1990fis** [comment]
I have moved evn variables on top of exec statement and still showing the same error.

**Comment by athieriot** [comment]
Ok.
There is something I don't understand with Env Variable on windows then.

Can you try to set them globally using the Settings utility?

http://xahlee.info/mswin/env_var.html

**Comment by krishna1990fis** [comment]
i think something is wrong in the way env variables are set on windows machine for hubot, for time being im directly hard coding the value of **access token** and **yammer group**. one more issue i am facing is this ->
![image](https://cloud.githubusercontent.com/assets/16776975/21609077/5b389ab8-d1e6-11e6-9da4-d8915edb5df9.png)

I  think if i solve this, i will be good to proceed on other things.

`[Tue Jan 03 2017 18:54:23 GMT+0530 (India Standard Time)] ERROR Error: No groups selected or ID resolution failed.
  at C:\Users\e3024650\myhubot\node_modules\hubot-yammer\src\yammer.coffee:139:17, <js>:213:17
  at Request._callback (C:\Users\e3024650\myhubot\node_modules\yammer\main.js:137:12)
  at Request.self.callback (C:\Users\e3024650\myhubot\node_modules\request\request.js:121:22)'

**Comment by krishna1990fis** [comment]
i think you have answered a similar question earlier to @anshumanpurohit  but that is again w.r.t Unix system.

**Comment by athieriot** [comment]
Is your group public?

Le mar. 3 janv. 2017 à 13:38, krishna1990fis <notifications@github.com> a
écrit :

**Comment by krishna1990fis** [comment]
Yes, i have made it public while creating it in the yammer

**Comment by krishna1990fis** [comment]
@athieriot Do u think i am missing any other configuration ? i am guessing hubot will make a call to yammer using a API and the token generated . I am still getting the above error.

**Comment by athieriot** [comment]
Could you please log into your Yammer account (The same you created the Token with) and try that URL in your browser please?

      https://www.yammer.com/api/v1/groups?mine=1

In the result, you should see one item that have a ```name``` property with the value __chatbot_Hubot__

Is suspect it's not in the list and that might be the issue.

**Comment by krishna1990fis** [comment]
I am able to see the chatbot_Hubot name in the response tag like this

`<email>chatbothubot+fisglobal.com@yammer.com</email>
<full-name>chatbot_Hubot</full-name>`

**Comment by athieriot** [comment]
Can you see a "name" property?

      <name>chatbot_hubot</name>

**Comment by krishna1990fis** [comment]
i can see these two in the response
<full-name>chatbot_Hubot</full-name>
<name>chatbothubot</name>

**Comment by athieriot** [comment]
Sorry to be insistent there but would you mind to paste the whole object corresponding to the chatbot_Hubot group please?

**Comment by krishna1990fis** [comment]
Here you go...
![image](https://cloud.githubusercontent.com/assets/16776975/21682197/4545b1fc-d379-11e6-9ab9-98e3221fd1e6.png)

**Comment by krishna1990fis** [comment]
Is that all or you want the complete XML object ?

**Comment by athieriot** [comment]
No it's perfect. I know what is happening.

Are you in a position to remove the "_" character in the group name?

If so, please try again without, if not, I'll prompt you to some change to
perform in yammer.coffee to use the "fullname" property instead.

In both case, I'll provide an update in hubot-yammer that fix this bug.

Thanks, I hope it's the last bit :)

Le jeu. 5 janv. 2017 à 13:33, krishna1990fis <notifications@github.com> a
écrit :

**Comment by krishna1990fis** [comment]
alright i ll make those changes and revert back. give me 2 min

**Comment by krishna1990fis** [comment]
i think i ll not be able to change the group name, i ll create new one and try

**Comment by athieriot** [comment]
Tell me if it's not possible and I'll show you the changes so you can try
locally.

Le jeu. 5 janv. 2017 à 14:13, krishna1990fis <notifications@github.com> a
écrit :

**Comment by krishna1990fis** [comment]
yeah please, because on name change im getting this error
![image](https://cloud.githubusercontent.com/assets/16776975/21683775/e07f915e-d380-11e6-919d-ea64ad8c1532.png)

**Comment by athieriot** [comment]
Ok. Could you please try first to change your HUBOT_YAMMER_GROUPS variable to "chatbothubot" (no underscore):

      set HUBOT_YAMMER_GROUPS="chatbothubot"

**Comment by krishna1990fis** [comment]
ok done, error is gone now 
![image](https://cloud.githubusercontent.com/assets/16776975/21684552/1744a816-d384-11e6-9b76-af105fccf780.png)

**Comment by athieriot** [comment]
Is Hubot responding?

**Comment by athieriot** [comment]
I don't expect anything happening there anymore. What have you tried in Yammer?

**Comment by krishna1990fis** [comment]
i tried **testbot help** in chatbot_Hubot group
![image](https://cloud.githubusercontent.com/assets/16776975/21684846/55515bb2-d385-11e6-951d-ff14c715d1f6.png)

**Comment by athieriot** [comment]
I wonder if you should invite (or add) the bot user to the group yourself.

**Comment by athieriot** [comment]
Pull Request has been created to try going around the underscore problem: https://github.com/athieriot/hubot-yammer/pull/29

**Comment by krishna1990fis** [comment]
In my case i have work email id and i am using the same account as bot user, How do i invite bot user to the group itself ?

I am thinking that i need to change the group name in yammer. because now i am using **chatbotHubot** as a group name but in yammer its **chatbot_Hubot**.

**Comment by athieriot** [comment]
As long as you can see the Group ID in the console, the Group is fine now.

But please note that hubot-yammer has been made so it won't reply to
itself, which mean that it will never reply to you (As you are the same
Yammer user)...

**Comment by krishna1990fis** [comment]
i am seriously confused !!! U mean to say that i need to have a separate hubot user ? if yes, how does that make a difference, because even if i have one, i will be adding him to the same group as another user.
Please clarifty

**Comment by athieriot** [comment]
You need to have a separate hubot user.
But the problem is not that it is in the same group as other users.

The problem here is that hubot is impersonate you (the owner of the token)
in order to communicate into Yammer.
Which means that when you ask for "testbot help" you are asking yourself
the question and Hubot deliberately ignore the message. (And it does so
because otherwise there would be some scenario where it would never stop
replying to itself in a loop)

It order to make sure I am right and your setup is working, you can ask
(right now, without changing anything) someone else at your company to talk
to hubot in the same channel. Normally, it would work and it should be your
avatar that is displayed in the reply)

If we ever manage to make it work for you I'll seriously update the README
to make sure there is enough details for the next guys

Le jeu. 5 janv. 2017 à 17:27, krishna1990fis <notifications@github.com> a
écrit :

**Comment by krishna1990fis** [comment]
@athieriot **OMG** thank you so much. its working now. you were right about the **impersonate** thing.
after i asked other members of my group on yammer to ask some question to hubot, they were able to get the reply from the hubot, and i was also able to see the logs on hubot console.

Thank you so much for your help and making this work. i really appreciate your effort in making this possible. Please make necessary changes to README. If anybody wants to implement this, they should not face all these kind of issues.
